version: '3.8'
services:
  tshock:
    build: ./tshock
    container_name: terraria_crimson_tshock
    ports:
      - "7777:7777"
      - "7878:7878"  # TShock REST API port
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/config/config.json:/terraria/tshock/config.json"
      - "./tshock/config/groups.json:/terraria/tshock/groups.json"
      - "./tshock/plugins:/terraria/ServerPlugins"
      - "./tshock/config/autoteam.json:/terraria/tshock/autoteam.json"
      - "./tshock/config/tcr.json:/terraria/tshock/tcr.json"
      - "./tshock/config/vote.json:/terraria/tshock/vote.json"
      - "./tshock/config/multisengine.json:/terraria/tshock/multisengine.json"
      - "./tshock/logs:/terraria/logs"
    restart: unless-stopped

  corruption:
    build: ./tshock
    container_name: terraria_tshock_corruption
    ports:
      - "7779:7777"  # Map external 7779 to internal 7777
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/config/config.json:/terraria/tshock/config.json"
      - "./tshock/config/groups.json:/terraria/tshock/groups.json"
      - "./tshock/plugins:/terraria/ServerPlugins"
      - "./tshock/config/autoteam.json:/terraria/tshock/autoteam.json"
      - "./tshock/config/tcr.json:/terraria/tshock/tcr.json"
      - "./tshock/config/vote.json:/terraria/tshock/vote.json"
      - "./tshock/config/multisengine.json:/terraria/tshock/multisengine.json"
      - "./tshock/logs:/terraria/logs"
      - "./tshock/serverconfig-corruption.txt:/terraria/serverconfig.txt"
    restart: unless-stopped

  multisengine:
    build: ./tshock
    container_name: terraria_multisengine
    ports:
      - "7778:7778"  # MultiSEngine port
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/logs:/terraria/logs"
      - "./tshock/serverconfig-mse.txt:/terraria/serverconfig.txt"
    restart: unless-stopped
    entrypoint: [
      "./TShock.Server",
      "-port", "7778",
      "-autocreate", "3",
      "-world", "/terraria/worlds/mse_lobby.wld",
      "-worldname", "mse_lobby",
      "-logpath", "/terraria/logs",
      "-logformat", "mse_log_{0:yyyy-MM-dd_HH-mm-ss}.log"
    ]

  # tmod:
  #   build: ./tmodloader
  #   container_name: terraria_tmod
  #   # We'll run this server on port 7778 to avoid conflict with TShock
  #   ports:
  #     - "7778:7778"
  #   volumes:
  #     - "./tmodloader/worlds:/terraria/worlds"
  #   restart: unless-stopped
