version: '3.8'
services:
  tshock:
    build: ./tshock
    container_name: terraria_tshock
    ports:
      - "7777:7777"
      - "7878:7878"  # TShock REST API port
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/config/config.json:/terraria/tshock/config.json"
      - "./tshock/config/groups.json:/terraria/tshock/groups.json"
    restart: unless-stopped

  # tmod:
  #   build: ./tmodloader
  #   container_name: terraria_tmod
  #   # We'll run this server on port 7778 to avoid conflict with TShock
  #   ports:
  #     - "7778:7778"
  #   volumes:
  #     - "./tmodloader/worlds:/terraria/worlds"
  #   restart: unless-stopped
