version: '3.8'
services:
  tshock:
    build: ./tshock
    container_name: terraria_crimson_tshock
    ports:
      - "7777:7777"
      - "7878:7878"  # TShock REST API port
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/logs:/terraria/logs"
      - "./tshock/serverconfig.txt:/terraria/serverconfig.txt"
      # Map entire directories instead of individual files
      - "./tshock/plugins:/terraria/ServerPlugins"
      - "./tshock/config:/terraria/tshock"
    restart: unless-stopped
    entrypoint: [
      "./TShock.Server",
      "-port", "7777",
      "-world", "/terraria/worlds/1hp.wld",
      "-logpath", "/terraria/logs",
      "-logformat", "server_log_{0:yyyy-MM-dd_HH-mm-ss}.log"
    ]

  corruption:
    build: ./tshock
    container_name: terraria_tshock_corruption
    ports:
      - "7779:7777"  # Map external 7779 to internal 7777
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/plugins:/terraria/ServerPlugins"
      - "./tshock/config:/terraria/tshock"
      - "./tshock/logs:/terraria/logs"
      - "./tshock/serverconfig-corruption.txt:/terraria/serverconfig.txt"
    restart: unless-stopped

  multisengine:
    build: ./tshock
    container_name: terraria_multisengine
    ports:
      - "7778:7778"  # MultiSEngine port
    volumes:
      - "./tshock/worlds:/terraria/worlds"
      - "./tshock/logs:/terraria/logs"
      - "./tshock/plugins:/terraria/ServerPlugins"
      - "./tshock/config:/terraria/tshock"
      - "./tshock/serverconfig-mse.txt:/terraria/serverconfig.txt"
    restart: unless-stopped
    entrypoint: [
      "./TShock.Server",
      "-port", "7778",
      "-autocreate", "3",
      "-world", "/terraria/worlds/mse_lobby.wld",
      "-worldname", "mse_lobby",
      "-logpath", "/terraria/logs",
      "-logformat", "mse_log_{0:yyyy-MM-dd_HH-mm-ss}.log"
    ]

  tmod:
    build: ./tmodloader
    container_name: terraria_tmod
    # We'll run this server on port 7780 as specified in the Dockerfile
    ports:
      - "7780:7780"
    volumes:
      - "./tmodloader/worlds:/tmodloader/worlds"
      - "./tmodloader/mods:/tmodloader/ModLoader/Mods"
    restart: unless-stopped
